export const scoresExample = [
  {
    league: "Premier League",
    round: "Matchweek 27",
    home: {
      clubName: "Liverpool FC",
      name: "Liverpool",
      abbreviation: "LIV",
      logo: "",
    },
    away: {
      clubName: "Manchester City FC",
      name: "Manchester City",
      abbreviation: "MCI",
      logo: "",
    },
    score: "2-1",
    time: "87'",
    date: "2024-01-01",
    venue: "Anfield",
    referees: ["Michael Oliver", "Stuart Attwell"],
    attendance: 54074,
    status: "live",
  },
  {
    league: "Premier League", 
    round: "Matchweek 26",
    home: {
      clubName: "Liverpool FC",
      name: "Liverpool",
      abbreviation: "LIV",
      logo: "",
    },
    away: {
      clubName: "Aston Villa FC",
      name: "Aston Villa",
      abbreviation: "AVL",
      logo: "",
    },
    score: "2-0",
    time: "FT",
    date: "2024-01-01",
    venue: "Anfield",
    referees: ["Michael Oliver", "Stuart Attwell"],
    attendance: 54074,
    status: "final",
  },
  {
    league: "FA Cup",
    round: "Round 4",
    home: {
      clubName: "Liverpool FC",
      name: "Liverpool",
      abbreviation: "LIV",
      logo: "",
    },
    away: {
      clubName: "Plymouth Argyle",
      name: "Plymouth Argyle",
      abbreviation: "PLY",
      logo: "",
    },
    score: null,
    time: null,
    date: "2025-04-01",
    venue: "Anfield",
    referees: ["Michael Oliver", "Stuart Attwell"],
    attendance: 54074,
    status: "upcoming",
  },
  {
    league: "NCAAM",
    round: "Regular Season",
    home: {
      clubName: "Duke University",
      name: "Duke",
      abbreviation: "DUK",
      logo: "",
    },
    away: {
      clubName: "The University of North Carolina",
      name: "North Carolina",
      abbreviation: "UNC",
      logo: "",
    },
    score: "89-79",
    time: "F",
    date: "2024-01-01",
    venue: "Cameron Indoor Stadium",
    referees: ["John Higgins", "Tom Washington"],
    attendance: 9314,
    status: "final",
  },
  {
    league: "NBA",
    round: "NBA Cup",
    home: {
      clubName: "Los Angeles Lakers",
      name: "Lakers",
      abbreviation: "LAL",
      logo: "",
    },
    away: {
      clubName: "Phoenix Suns",
      name: "Suns",
      abbreviation: "PHX",
      logo: "",
    },
    score: "102-99",
    time: "F",
    date: "2024-01-01",
    venue: "Staples Center",
    referees: ["Brent Barnaky", "Kyle Anderson"],
    attendance: 18997,
    status: "final",
  },
];
